language: node_js
os: linux
sudo: required
dist: trusty
group: deprecated-2017Q4
bundler_args: --retry 5
node_js:
  - "7"
env:
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=
before_install:
- sudo apt-get install -y xserver-xorg-dev libxext-dev libxi-dev 
install:
- npm install --silent -g phantomjs 
- npm install --silent -g casperjs 
- npm install --silent -g slimerjs
- npm install --silent -g gl
- npm config set registry http://registry.npmjs.org/

services:
  - docker
addons:
  firefox: "58.0"
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
    - net-tools
    - lsof
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export SLIMERJSLAUNCHER=/home/travis/firefox-58.0/firefox/firefox
  - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
script:
  - npm config set registry http://registry.npmjs.org/
  - echo "Current time :$(date +"%T")"
  - docker --version 
